from playwright.sync_api import Playwright, expect

def test_gestionar_documentos(playwright: Playwright) -> None:
    archivo_prueba = __file__.replace("test_gestionar_documentos.py", "archivo_prueba.pdf")

    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://127.0.0.1:8000/")
    page.get_by_role("link", name="Portal Agente Origen").click()
    page.get_by_role("textbox", name="Username:").click()
    page.get_by_role("textbox", name="Username:").fill("u1")
    page.get_by_role("textbox", name="Password:").click()
    page.get_by_role("textbox", name="Password:").fill("Contra1234")
    page.get_by_role("button", name="Ingresar").click()
    page.get_by_role("link", name="Nuevo Embarque").click()
    page.get_by_label("Ruta:").select_option("1")
    page.get_by_role("textbox", name="Fecha salida:").fill("2025-07-10")
    page.get_by_label("Buque:").select_option("BR0001")
    page.get_by_role("textbox", name="Nombre transportista:").click()
    page.get_by_role("textbox", name="Nombre transportista:").fill("Transportista")
    page.get_by_role("textbox", name="Nombre mc:").click()
    page.get_by_role("textbox", name="Nombre mc:").fill("MC")
    page.get_by_role("button", name="Doc mc:").set_input_files(archivo_prueba)
    page.get_by_role("button", name="Crear").click()
    page.get_by_role("link", name="Crear Contenedor").click()
    page.get_by_label("Tipo contenedor:").select_option("40GP")
    page.get_by_label("Tipo carga:").select_option("1")
    page.get_by_label("Tipo equipamiento:").select_option("6")
    page.get_by_label("Puerto descarga:").select_option("NL001")
    page.get_by_role("button", name="Guardar").click()
    page.locator("#id_descripcion_mercancia").click()
    page.locator("#id_descripcion_mercancia").fill("Desc")
    page.locator("#id_cantidad_bultos").click()
    page.locator("#id_cantidad_bultos").press("ArrowUp")
    page.locator("#id_bulto").select_option("1")
    page.locator("#id_pais").select_option("CN")
    page.get_by_role("button", name="Agregar Mercancía").click()
    page.get_by_role("link", name="Siguiente ➜").click()
    page.locator("#id_bol-nombre_archivo").click()
    page.locator("#id_bol-nombre_archivo").fill("b")
    page.locator("#id_bol-archivo").click()
    page.locator("#id_bol-nombre_archivo").click()
    page.locator("#id_bol-nombre_archivo").fill("Bill of lading")
    page.locator("#id_bol-archivo").set_input_files(archivo_prueba)
    page.locator("#id_fac-nombre_archivo").click()
    page.locator("#id_fac-nombre_archivo").fill("Factura de Exportación")
    page.locator("#id_fac-archivo").set_input_files(archivo_prueba)
    page.get_by_role("button", name="Guardar Factura").click()
    page.locator("#id_bol-nombre_archivo").click()
    page.locator("#id_bol-nombre_archivo").fill("Bill of Lading")
    page.locator("#id_bol-archivo").set_input_files(archivo_prueba)
    page.get_by_role("button", name="Guardar Bill of Lading").click()
    page.get_by_role("heading", name="Factura de Exportación").click()
    page.get_by_role("heading", name="Factura de Exportación").click()
    page.locator("#id_cert-nombre_archivo").click()
    page.locator("#id_cert-nombre_archivo").fill("Certificado de Origen")
    page.locator("#id_cert-archivo").set_input_files(archivo_prueba)
    page.get_by_role("button", name="Guardar Certificado").click()
    page.get_by_role("link", name="Siguiente").click()
    page.get_by_role("link", name="← Volver al listado de").click()
    expect(page.get_by_role("button", name="Enviar")).to_be_visible()
    page.once("dialog", lambda dialog: dialog.accept())
    page.get_by_role("button", name="Enviar").click()
    page.get_by_role("button", name="Cerrar sesión").click()
    page.get_by_role("link", name="Portal Agente Destino").click()
    page.get_by_role("textbox", name="Username:").click()
    page.get_by_role("textbox", name="Username:").fill("u3")
    page.get_by_role("textbox", name="Password:").click()
    page.get_by_role("textbox", name="Password:").fill("Contra1234")
    page.get_by_role("button", name="Ingresar").click()
    expect(page.get_by_role("cell", name="Puerto de Los Ángeles")).to_be_visible()
    page.get_by_role("link", name="Ver").click()
    expect(page.get_by_role("cell", name="Manifiesto de carga")).to_be_visible()
    page.get_by_role("button", name="Validar").click()
    page.get_by_role("link", name="← Volver al listado de").click()
    expect(page.get_by_role("cell", name="Finalizado")).to_be_visible()

    context.close()
    browser.close()
