# Generated by Django 5.2.1 on 2025-06-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id_bulto', models.AutoField(primary_key=True, serialize=False)),
                ('clase_bulto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarga',
            fields=[
                ('id_tipo_carga', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_carga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContenedor',
            fields=[
                ('id_tipo_cont', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_tipo_cont', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id_contenedor', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('es_consolidado', models.BooleanField(default=False)),
                ('embarque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores', to='embarque.embarque')),
                ('puerto_descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_destino', to='embarque.puerto')),
                ('puerto_procedencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_origen', to='embarque.puerto')),
                ('tipo_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores', to='contenedor.tipocarga')),
                ('tipo_contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores', to='contenedor.tipocontenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('estado_doc', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('descripcion_doc', models.TextField(blank=True)),
                ('documento', models.BinaryField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contenedor.contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id_equipamiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_equip', models.CharField(max_length=50)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='contenedor.contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id_mercancia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_mercancia', models.TextField()),
                ('cantidad_bultos', models.PositiveIntegerField()),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bulto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias', to='contenedor.bulto')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercancias', to='contenedor.contenedor')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercancias', to='embarque.pais')),
            ],
        ),
    ]
