# Generated by Django 5.2.1 on 2025-06-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='equipamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamiento_contenedor', to='contenedor.equipamiento'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_carga', to='contenedor.tipocarga'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_contenedor', to='contenedor.tipocontenedor'),
        ),
    ]
