# Generated by Django 5.2.1 on 2025-06-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0001_initial'),
        ('embarque', '0002_alter_escala_options_alter_escala_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='contenedor',
        ),
        migrations.RemoveField(
            model_name='mercancia',
            name='peso_bruto',
        ),
        migrations.AddField(
            model_name='bulto',
            name='peso_bulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='equipamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamiento_contenedor', to='contenedor.equipamiento'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='estado_contenedor',
            field=models.CharField(choices=[('En tránsito', 'En tránsito'), ('Arribado', 'Arribado'), ('Revocado', 'Revocado')], default='En tránsito', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to='embarque.embarque'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='id_contenedor',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga',
            field=models.ForeignKey(default='SV001', on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_destino', to='embarque.puerto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_procedencia',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_origen', to='embarque.puerto'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_carga', to='contenedor.tipocarga'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_contenedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_contenedor', to='contenedor.tipocontenedor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='contenedor.tipodocumento'),
        ),
    ]
