# Generated by Django 5.2.1 on 2025-06-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0002_tipodocumento_remove_documento_documento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamiento',
            new_name='TipoEquipamiento',
        ),
    ]
