# Generated by Django 5.2.1 on 2025-06-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0002_contenedor_equipamiento_alter_contenedor_tipo_carga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='contenedor',
        ),
    ]
