# Generated by Django 5.2.1 on 2025-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0003_rename_equipamiento_tipoequipamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocarga',
            name='descripcion_tipo_carga',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipocontenedor',
            name='nombre_tipo_cont',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoequipamiento',
            name='descripcion_equip',
            field=models.CharField(max_length=100),
        ),
    ]
