# Generated by Django 5.2.1 on 2025-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_tipodocumento_alter_documento_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
