# Generated by Django 5.2.1 on 2025-06-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_alter_tipocarga_descripcion_tipo_carga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='equipamiento',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='tipo_equipamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_equipamiento', to='contenedor.tipoequipamiento'),
        ),
    ]
