# Generated by Django 5.2.1 on 2025-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0005_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercancia',
            name='peso_bruto',
        ),
        migrations.AddField(
            model_name='bulto',
            name='peso_bulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
