# Generated by Django 5.2.1 on 2025-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0005_remove_contenedor_equipamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='id_contenedor',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
