# Generated by Django 5.2.1 on 2025-06-19 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0006_alter_contenedor_id_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulto',
            name='peso_bulto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='bulto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercancias', to='contenedor.bulto'),
        ),
    ]
