# Generated by Django 5.2.1 on 2025-06-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0006_remove_mercancia_peso_bruto_bulto_peso_bulto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='documento',
        ),
    ]
