# Generated by Django 5.2.1 on 2025-06-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0007_remove_documento_documento'),
        ('embarque', '0007_embarque_modo_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_procedencia',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_origen', to='embarque.puerto'),
        ),
    ]
