# Generated by Django 5.2.1 on 2025-06-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0008_alter_contenedor_puerto_procedencia'),
        ('embarque', '0009_alter_embarque_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='equipamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamiento_contenedor', to='contenedor.equipamiento'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_destino', to='embarque.puerto'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_carga', to='contenedor.tipocarga'),
        ),
    ]
