# Generated by Django 5.2.1 on 2025-06-04 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0009_alter_contenedor_equipamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='equipamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamiento_contenedor', to='contenedor.equipamiento'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_carga', to='contenedor.tipocarga'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_contenedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_contenedor', to='contenedor.tipocontenedor'),
        ),
    ]
