# Generated by Django 5.2.1 on 2025-06-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0010_alter_contenedor_equipamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Archivo',
            new_name='archivo',
        ),
    ]
