# Generated by Django 5.2.1 on 2025-06-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0011_rename_archivo_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='estado_contenedor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Arribado'), (2, 'En tránsito'), (3, 'Llegado')], default=1),
        ),
    ]
