# Generated by Django 5.2.1 on 2025-06-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0012_contenedor_estado_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='estado_contenedor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En tránsito'), (2, 'Arribado'), (3, 'Revocado')], default=2),
        ),
    ]
