# Generated by Django 5.2.1 on 2025-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0013_alter_contenedor_estado_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='estado_contenedor',
            field=models.CharField(choices=[('En tránsito', 'En tránsito'), ('Arribado', 'Arribado'), ('Revocado', 'Revocado')], default='En tránsito', max_length=20),
        ),
    ]
