# Generated by Django 5.2.1 on 2025-06-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0014_alter_contenedor_estado_contenedor'),
        ('embarque', '0009_alter_embarque_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to='embarque.embarque'),
        ),
    ]
