# Generated by Django 5.2.1 on 2025-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0016_alter_tipodocumento_nombre_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre_tipo_doc',
            field=models.CharField(default='Sin nombre', max_length=50),
            preserve_default=False,
        ),
    ]
