# Generated by Django 5.2.1 on 2025-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0017_alter_documento_nombre_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='id_contenedor',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
