# Generated by Django 5.2.1 on 2025-06-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0019_documento_validado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='validado_por',
        ),
    ]
