# Generated by Django 5.2.1 on 2025-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Agente naviero de origen', 'Agente naviero de origen'), ('Agente naviero de destino', 'Agente naviero de destino')], max_length=30),
        ),
    ]
