# Generated by Django 5.2.1 on 2025-06-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0001_initial'),
        ('usuarios', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais', to='embarque.pais'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puerto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puerto', to='embarque.puerto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Agente aduanal de origen', 'Agente aduanal de origen'), ('Agente aduanal de destino', 'Agente aduanal de destino')], max_length=30),
        ),
    ]
