# Generated by Django 5.2.1 on 2025-06-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id_buque', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre_buque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id_embarque', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('nombre_transportista', models.CharField(blank=True, max_length=20)),
                ('modo_transporte', models.CharField(blank=True, max_length=8)),
                ('buque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='embarque.buque')),
                ('pais_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_destino', to='embarque.pais')),
                ('pais_procedencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_origen', to='embarque.pais')),
            ],
        ),
        migrations.CreateModel(
            name='ManifiestoCarga',
            fields=[
                ('id_mc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('doc_mc', models.BinaryField(blank=True, null=True)),
                ('nombre_mc', models.CharField(max_length=50)),
                ('embarque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto', to='embarque.embarque')),
            ],
        ),
        migrations.AddField(
            model_name='buque',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buques', to='embarque.pais'),
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id_puerto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_puerto', models.CharField(max_length=20)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puertos', to='embarque.pais')),
            ],
        ),
        migrations.AddField(
            model_name='embarque',
            name='puerto_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_destino', to='embarque.puerto'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='puerto_procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_origen', to='embarque.puerto'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques', to='embarque.ruta'),
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('orden_escala', models.PositiveIntegerField()),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='embarque.embarque')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='embarque.puerto')),
            ],
            options={
                'ordering': ['embarque', 'orden_escala'],
                'unique_together': {('puerto', 'embarque', 'orden_escala')},
            },
        ),
        migrations.CreateModel(
            name='SegmentoRuta',
            fields=[
                ('id_segmento_ruta', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('orden_ruta', models.PositiveIntegerField()),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segmentos', to='embarque.puerto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='embarque.ruta')),
            ],
            options={
                'ordering': ['ruta', 'orden_ruta'],
                'unique_together': {('puerto', 'ruta', 'orden_ruta')},
            },
        ),
    ]
