# Generated by Django 5.2.1 on 2025-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segmentoruta',
            unique_together={('ruta', 'orden_ruta')},
        ),
        migrations.AddField(
            model_name='ruta',
            name='puertos',
            field=models.ManyToManyField(related_name='rutas', through='embarque.SegmentoRuta', to='embarque.puerto'),
        ),
        migrations.AddField(
            model_name='segmentoruta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='segmentoruta',
            name='id_segmento_ruta',
        ),
    ]
