# Generated by Django 5.2.1 on 2025-06-12 15:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) Ajustes de opciones y restricciones únicas
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['orden_escala']},
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('embarque', 'orden_escala')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentoruta',
            unique_together={('ruta', 'orden_ruta')},
        ),

        # 2) Primero quito las PK antiguas
        migrations.RemoveField(
            model_name='escala',
            name='id_escala',
        ),
        migrations.RemoveField(
            model_name='segmentoruta',
            name='id_segmento_ruta',
        ),

        # 3) Ahora añado los nuevos AutoField PK
        migrations.AddField(
            model_name='escala',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            ),
        ),
        migrations.AddField(
            model_name='segmentoruta',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            ),
        ),

        # 4) Resto de AddField a otros modelos
        migrations.AddField(
            model_name='embarque',
            name='agente_origen',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='embarques_origen',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='embarque',
            name='estado',
            field=models.CharField(
                choices=[('borrador', 'borrador'), ('enviado', 'enviado')],
                default='borrador',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='embarque',
            name='orden_actual',
            field=models.PositiveIntegerField(
                default=0,
                help_text='0 = aún no ha zarpado; 1 = salió del 1er puerto, etc.'
            ),
        ),
        migrations.AddField(
            model_name='embarque',
            name='puerto_actual',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques_actual',
                to='embarque.puerto'
            ),
        ),
        migrations.AddField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(
                choices=[('Denegado', 'Denegado'), ('Aprobado', 'Aprobado')],
                default='Denegado',
                help_text='Estado del manifiesto de carga',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='manifiestocarga',
            name='validado_por',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario que validó el manifiesto',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='manifiestos_validacion',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='ruta',
            name='puertos',
            field=models.ManyToManyField(
                related_name='rutas',
                through='embarque.SegmentoRuta',
                to='embarque.puerto'
            ),
        ),

        # 5) AlterField: defaults válidos y sin formato dd/mm/yyyy
        migrations.AlterField(
            model_name='embarque',
            name='fecha_salida',
            field=models.DateField(
                default=datetime.date(2025, 6, 12),
                help_text='Fecha de salida del buque'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embarque',
            name='id_embarque',
            field=models.CharField(
                editable=False, max_length=7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='nombre_transportista',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='pais_destino',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques_destino',
                to='embarque.pais'
            ),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='pais_procedencia',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques_origen',
                to='embarque.pais'
            ),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='puerto_destino',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques_destino',
                to='embarque.puerto'
            ),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='puerto_procedencia',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques_origen',
                to='embarque.puerto'
            ),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='ruta',
            field=models.ForeignKey(
                default='1',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embarques',
                to='embarque.ruta'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escala',
            name='orden_escala',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='doc_mc',
            field=models.FileField(
                default='manifiestos/plantilla.pdf',
                upload_to='manifiestos/'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='embarque',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='manifiesto_carga',
                to='embarque.embarque'
            ),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='id_mc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='id_puerto',
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='segmentoruta',
            name='puerto',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='segmentos',
                to='embarque.puerto'
            ),
        ),
    ]
