# Generated by Django 5.2.1 on 2025-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0002_alter_segmentoruta_unique_together_ruta_puertos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='id_puerto',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
