# Generated by Django 5.2.1 on 2025-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0002_alter_escala_options_alter_escala_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='nombre_puerto',
            field=models.CharField(max_length=50),
        ),
    ]
