# Generated by Django 5.2.1 on 2025-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0003_alter_puerto_id_puerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='id_escala',
        ),
        migrations.AddField(
            model_name='escala',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
