# Generated by Django 5.2.1 on 2025-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0004_alter_ruta_nombre_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(choices=[('Denegado', 'Denegado'), ('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente')], default='Denegado', help_text='Estado del manifiesto de carga', max_length=20),
        ),
    ]
