# Generated by Django 5.2.1 on 2025-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0004_remove_escala_id_escala_escala_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['orden_escala']},
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='escala',
            name='orden_escala',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('embarque', 'orden_escala')},
        ),
    ]
