# Generated by Django 5.2.1 on 2025-06-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0005_alter_escala_options_alter_escala_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='modo_transporte',
        ),
        migrations.AlterField(
            model_name='embarque',
            name='id_embarque',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='pais_destino',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_destino', to='embarque.pais'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='pais_procedencia',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_origen', to='embarque.pais'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='puerto_destino',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_destino', to='embarque.puerto'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='puerto_procedencia',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_origen', to='embarque.puerto'),
        ),
    ]
