# Generated by Django 5.2.1 on 2025-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0006_remove_embarque_modo_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='modo_transporte',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
