# Generated by Django 5.2.1 on 2025-06-03 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0007_embarque_modo_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarque',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
