# Generated by Django 5.2.1 on 2025-06-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0008_alter_embarque_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarque',
            name='fecha_salida',
            field=models.DateField(help_text='Fecha de salida del buque'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='nombre_transportista',
            field=models.CharField(help_text='Debe tener al menos 3 letras (validación en formulario)', max_length=20),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='embarque.ruta'),
        ),
    ]
