# Generated by Django 5.2.1 on 2025-06-06 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0009_alter_embarque_fecha_salida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='gente_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embarques_origen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='doc_mc',
            field=models.FileField(blank=True, null=True, upload_to='manifiestos/'),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='embarque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto_carga', to='embarque.embarque'),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='id_mc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
