# Generated by Django 5.2.1 on 2025-06-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0010_embarque_gente_origen_alter_manifiestocarga_doc_mc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embarque',
            old_name='gente_origen',
            new_name='agente_origen',
        ),
    ]
