# Generated by Django 5.2.1 on 2025-06-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0011_rename_gente_origen_embarque_agente_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='doc_mc',
            field=models.FileField(upload_to='manifiestos/'),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='embarque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto_carga', to='embarque.embarque'),
        ),
    ]
