# Generated by Django 5.2.1 on 2025-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0012_alter_manifiestocarga_doc_mc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(choices=[('Denegado', 'En proceso'), ('Aprobado', 'Finalizado')], default='Denegado', help_text='Estado del manifiesto de carga', max_length=20),
        ),
    ]
