# Generated by Django 5.2.1 on 2025-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0013_manifiestocarga_estado_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(choices=[('Denegado', 'Denegado'), ('Aprobado', 'Aprobado')], default='Denegado', help_text='Estado del manifiesto de carga', max_length=20),
        ),
    ]
