# Generated by Django 5.2.1 on 2025-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0014_alter_manifiestocarga_estado_mc'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiestocarga',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado')], default='Borrador', max_length=10),
        ),
    ]
