# Generated by Django 5.2.1 on 2025-06-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0015_manifiestocarga_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='estado',
            field=models.CharField(choices=[('borrador', 'borrador'), ('enviado', 'enviado')], default='borrador', max_length=10),
        ),
    ]
