# Generated by Django 5.2.1 on 2025-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0016_alter_manifiestocarga_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiestocarga',
            name='estado',
        ),
        migrations.AddField(
            model_name='embarque',
            name='estado',
            field=models.CharField(choices=[('borrador', 'borrador'), ('enviado', 'enviado')], default='borrador', max_length=10),
        ),
    ]
