# Generated by Django 5.2.1 on 2025-06-09 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0017_remove_manifiestocarga_estado_embarque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='puerto_actual',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_actual', to='embarque.escala'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='nombre_transportista',
            field=models.CharField(max_length=20),
        ),
    ]
