# Generated by Django 5.2.1 on 2025-06-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0018_embarque_puerto_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarque',
            name='puerto_actual',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques_actual', to='embarque.puerto'),
        ),
    ]
