# Generated by Django 5.2.1 on 2025-06-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0019_alter_embarque_puerto_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentoruta',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='embarque.puerto'),
        ),
    ]
