# Generated by Django 5.2.1 on 2025-06-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0020_alter_segmentoruta_puerto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiestocarga',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que validó el manifiesto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifiestos_validacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
