# Generated by Django 5.2.1 on 2025-06-10 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0021_manifiestocarga_validado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Denegado', 'Denegado'), ('Aprobado', 'Aprobado')], default='Pendiente', help_text='Estado del manifiesto de carga', max_length=20),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifiestos_validacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
