# Generated by Django 5.2.1 on 2025-06-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0022_alter_manifiestocarga_estado_mc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestocarga',
            name='estado_mc',
            field=models.CharField(choices=[('Denegado', 'Denegado'), ('Aprobado', 'Aprobado')], default='Denegado', help_text='Estado del manifiesto de carga', max_length=20),
        ),
        migrations.AlterField(
            model_name='manifiestocarga',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que validó el manifiesto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifiestos_validacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
