# Generated by Django 5.2.1 on 2025-06-10 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0023_alter_manifiestocarga_estado_mc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='validao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
