# Generated by Django 5.2.1 on 2025-06-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0024_embarque_validao_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embarque',
            old_name='validao_por',
            new_name='validado_por',
        ),
    ]
