# Generated by Django 5.2.1 on 2025-06-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0025_rename_validao_por_embarque_validado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='validado_por',
        ),
    ]
