# Generated by Django 5.2.1 on 2025-06-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarque', '0027_manifiestocarga_orden_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiestocarga',
            name='orden_actual',
        ),
        migrations.AddField(
            model_name='embarque',
            name='orden_actual',
            field=models.PositiveIntegerField(default=0, help_text='0 = aún no ha zarpado; 1 = salió del 1er puerto, etc.'),
        ),
    ]
